/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connectfour;

import javax.swing.JLabel;

/**
 *
 * @author Lia
 */
public class JFrameConnectFour extends javax.swing.JFrame
{

    char[][] gameBoard;
    Logic logic;
    AI ai;
    boolean hotSeat;

    /**
     * Creates new form JFrameConnectFour
     */
    public JFrameConnectFour()
    {
        initComponents();
        Initialize();
        /*    HotSeatOrAI();
         if (!hotSeat)
         {
         LevelSelection();
         }
         RunOneGame();*/

    }

    private void Initialize()
    {
        this.logic = new Logic();
        this.gameBoard = logic.GetBoard();
        this.hotSeat = true;
        this.jLabelPlayer1Marker.setVisible(false);
        this.jLabelPlayer2MarkerChoice.setVisible(false);
        this.jComboBoxPlayer2MarkerChoice.setVisible(false);
        this.jLabelPlayer2Marker.setVisible(false);
        this.jLabelDifficultyChoice.setVisible(false);
        this.jComboBoxDifficutlyChoice.setVisible(false);
        this.jLabelAIAnswer.setVisible(false);
        this.jComboBoxAIChoice.setVisible(false);
        this.jLabelAIChoice.setVisible(false);
        this.jComboBoxPlayer1MarkerChoice.setModel(new javax.swing.DefaultComboBoxModel(Marker.GetOptions()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabelConnectFourTitle = new javax.swing.JLabel();
        jComboBoxPlayer1MarkerChoice = new javax.swing.JComboBox();
        jLabelPlayer1MarkerChoice = new javax.swing.JLabel();
        jLabelPlayer2MarkerChoice = new javax.swing.JLabel();
        jComboBoxPlayer2MarkerChoice = new javax.swing.JComboBox();
        jComboBoxDifficutlyChoice = new javax.swing.JComboBox();
        jLabelDifficultyChoice = new javax.swing.JLabel();
        jLabelPlayer1Marker = new javax.swing.JLabel();
        jComboBoxAIChoice = new javax.swing.JComboBox();
        jLabelPlayer2Marker = new javax.swing.JLabel();
        jLabelAIAnswer = new javax.swing.JLabel();
        jLabelAIChoice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelConnectFourTitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabelConnectFourTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConnectFourTitle.setText("Connect Four");

        jComboBoxPlayer1MarkerChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPlayer1MarkerChoice.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxPlayer1MarkerChoiceActionPerformed(evt);
            }
        });

        jLabelPlayer1MarkerChoice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabelPlayer1MarkerChoice.setText("Player 1 Marker");

        jLabelPlayer2MarkerChoice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabelPlayer2MarkerChoice.setText("Player 2 Marker");

        jComboBoxPlayer2MarkerChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxDifficutlyChoice.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jComboBoxDifficutlyChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelDifficultyChoice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabelDifficultyChoice.setText("Difficulty");

        jLabelPlayer1Marker.setText("jLabel1");

        jComboBoxAIChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelPlayer2Marker.setText("jLabel2");

        jLabelAIAnswer.setText("jLabel3");

        jLabelAIChoice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabelAIChoice.setText("Set Player 2 to AI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDifficutlyChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDifficultyChoice)
                    .addComponent(jComboBoxAIChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPlayer2MarkerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPlayer1MarkerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlayer2MarkerChoice)
                            .addComponent(jLabelAIChoice)
                            .addComponent(jLabelPlayer1MarkerChoice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlayer1Marker)
                            .addComponent(jLabelAIAnswer)
                            .addComponent(jLabelPlayer2Marker))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabelConnectFourTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelConnectFourTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlayer1MarkerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlayer1Marker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPlayer1MarkerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlayer2MarkerChoice)
                    .addComponent(jLabelPlayer2Marker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPlayer2MarkerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAIChoice)
                    .addComponent(jLabelAIAnswer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAIChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDifficultyChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDifficutlyChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPlayer1MarkerChoiceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxPlayer1MarkerChoiceActionPerformed
    {//GEN-HEADEREND:event_jComboBoxPlayer1MarkerChoiceActionPerformed
        // TODO add your handling code here:
        int player1Marker = this.jComboBoxPlayer1MarkerChoice.getSelectedIndex();
       if(player1Marker >= 0 && player1Marker < Marker.GetOptions().length)
       {
           this.logic.SetMarkerPlayer1(player1Marker);
           this.jComboBoxPlayer1MarkerChoice.setVisible(false);
           this.jLabelPlayer1Marker.setText(this.logic.GetPlayer1() + "");
           this.jLabelPlayer1Marker.setVisible(true);
           this.jLabelPlayer2MarkerChoice.setVisible(true);
           this.jComboBoxPlayer2MarkerChoice.setVisible(true);
           this.jComboBoxPlayer2MarkerChoice.setModel(new javax.swing.DefaultComboBoxModel(Marker.GetOptions(player1Marker)));
       }
    }//GEN-LAST:event_jComboBoxPlayer1MarkerChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrameConnectFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrameConnectFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrameConnectFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrameConnectFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFrameConnectFour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxAIChoice;
    private javax.swing.JComboBox jComboBoxDifficutlyChoice;
    private javax.swing.JComboBox jComboBoxPlayer1MarkerChoice;
    private javax.swing.JComboBox jComboBoxPlayer2MarkerChoice;
    private javax.swing.JLabel jLabelAIAnswer;
    private javax.swing.JLabel jLabelAIChoice;
    private javax.swing.JLabel jLabelConnectFourTitle;
    private javax.swing.JLabel jLabelDifficultyChoice;
    private javax.swing.JLabel jLabelPlayer1Marker;
    private javax.swing.JLabel jLabelPlayer1MarkerChoice;
    private javax.swing.JLabel jLabelPlayer2Marker;
    private javax.swing.JLabel jLabelPlayer2MarkerChoice;
    // End of variables declaration//GEN-END:variables
}
